### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [laurenhoover/prj-rev-bwfs-tea-cozy#2]
(Simplify) Alternatively, you can use commas to separate multiple selectors sharing the same properties:

```css
h2, h3, h4 {
  padding: 10px;
  margin: 0;
}
```

https://github.com/laurenhoover/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/resources/css/style.css#L34-L45
