### ISSUE TITLE
Backup Font Families

### ISSUE THREAD

**Issue by cyouh95** [laurenhoover/prj-rev-bwfs-tea-cozy#3]
(Subtlety) It could be good practice to list some additional font families in case a browser does not support your first-choice font, there are others to [fall back](https://www.w3schools.com/cssref/pr_font_font-family.asp) on

```css
body {
  font-family: "Helvetica", sans-serif;
}
```

https://github.com/laurenhoover/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/resources/css/style.css#L2
