### ISSUE TITLE
Linking Images

### ISSUE THREAD

**Issue by cyouh95** [laurenhoover/prj-rev-bwfs-tea-cozy#4]
(Important) Be careful when you are linking an absolute file path to your image. Remember that this is specific to your computer and when I try to test your page, I will not have access to them. One way you can fix this is to use the direct url to the image:

```css
#mission {  
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-mission-background.jpg");
}
```

Alternatively, you may use the relative path to the images folder you've also pushed here:

```css
#mission {
  background-image: url("../images/img-mission-background.jpg");
}
```

https://github.com/laurenhoover/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/resources/css/style.css#L58
